name: Cass Config Builder Build & Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_operator_docker:
    name: Build Cass Config Builder Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: true
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Login to DockerHub
        if: ${{ !env.ACT }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
          java-version: 1.8
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: ./gradlew test

      # - name: Run tests
      #   if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == 'datastax/cass-config-builder'
      #   env:
      #     ORG_GRADLE_PROJECT_dockerRegistry: docker.pkg.github.com
      #     ORG_GRADLE_PROJECT_dockerRegistryUsername: ${{ github.actor }}
      #     ORG_GRADLE_PROJECT_dockerRegistryPassword: ${{ secrets.GITHUB_TOKEN }}
      #   uses: eskatos/gradle-command-action@v1
      #   with:
      #     gradle-version: 6.0.1
      #     arguments: test
      - name: Build docker image
        env:
          GITHUB_REPO_OWNER: ${{ github.repository_owner }}
        run: |
          export GITHUB_REPO_URL="https://github.com/${{ github.repository }}"
          ./scripts/build-push-images.sh
      - name: Archive build logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: gradle-logs
          path: build/reports
  